@MiniShopAPI_HostAddress = http://localhost:5079/api/products

GET {{MiniShopAPI_HostAddress}}
Accept: application/json

###

GET {{MiniShopAPI_HostAddress}}/fbc88a88-c6f4-42cc-b44e-9d0599f59b12
Accept: application/json

###
POST {{MiniShopAPI_HostAddress}}
Content-Type: application/json

{
  "id": "00000000-0000-0000-0000-000000000000",
  "name": "Test Product",
  "price": 12.5,
  "description": "A sample product for testing"
}

###
PUT {{MiniShopAPI_HostAddress}}
Content-Type: application/json

{
  "id": "fbc88a88-c6f4-42cc-b44e-9d0599f59b12",
  "name": "Test Product 2",
  "price": 300,
  "description": "A sample product for testing"
}

###
DELETE {{MiniShopAPI_HostAddress}}/fbc88a88-c6f4-42cc-b44e-9d0599f59b12
Content-Type: application/json

###
